service: microservicio-productos
org: parislht

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 1024
  timeout: 30
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::418047659300:role/LabRole
  environment:
    TABLE_NAME_PRODUCTS: ${sls:stage}-t_libros
    VALIDAR_TOKEN_FUNC: ${sls:stage}-ValidarTokenAcceso

functions:
  CrearProducto:
    handler: src/productos/CrearProducto.handler
    events:
      - http:
          path: productos/crear
          method: post
          cors: true

  ModificarProducto:
    handler: src/productos/ModificarProducto.handler
    events:
      - http:
          path: productos/modificar
          method: post
          cors: true

  EliminarProducto:
    handler: src/productos/EliminarProducto.handler
    events:
      - http:
          path: productos/eliminar
          method: post
          cors: true

  BuscarProducto:
    handler: src/productos/BuscarProducto.handler
    events:
      - http:
          path: productos/buscar
          method: get
          cors: true

  ListarProductos:
    handler: src/productos/ListarProductos.handler
    events:
      - http:
          path: productos/listar
          method: get
          cors: true

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PRODUCTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: libro_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: libro_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
