org: parislht
service: microservicio-productos

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::418047659300:role/LabRole
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME_PRODUCTS: ${sls:stage}-t_libro
    VALIDAR_TOKEN_FUNC: ${sls:stage}-ValidarTokenAcceso

functions:
  crearProducto:
    handler: CrearProducto.handler
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true
          integration: lambda

  modificarProducto:
    handler: ModificarProducto.handler
    events:
      - http:
          path: /productos/modificar
          method: post
          cors: true
          integration: lambda

  eliminarProducto:
    handler: EliminarProducto.handler
    events:
      - http:
          path: /productos/eliminar
          method: post
          cors: true
          integration: lambda

  buscarProducto:
    handler: BuscarProducto.handler
    events:
      - http:
          path: /productos/buscar
          method: get
          cors: true
          integration: lambda

  listarProductos:
    handler: ListarProductos.handler
    events:
      - http:
          path: /productos/listar
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaLibros:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME_PRODUCTS}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: libro_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: libro_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
